CREATE TABLE users (
  id VARCHAR NOT NULL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR(100) NOT NULL,
  token_key TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)