CREATE TABLE posts (
  id VARCHAR NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  teaser TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published BOOLEAN NOT NULL DEFAULT 'f'
)
